workflows:
  ios_unsigned_ipa:
    name: iOS Unsigned IPA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter precache --ios
      - |
        cd ios
        pod repo update
        pod install
        cd ..
      - flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
