name: Build iOS IPA (Flutter)
on: [workflow_dispatch]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter deps
        run: |
          flutter pub get
          flutter precache --ios
      - name: (Optional) Install CocoaPods deps
        run: |
          cd ios
          pod repo update
          pod install
      - name: Build unsigned IPA
        run: |
          # Add --flavor and/or --target if your app uses them
          flutter build ipa --release --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
